name: Trigger Netlify Build
on:
  schedule:
    # Run at 9:55 daily
    - cron: '00 10 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.netlify_hook_id }}
        
